/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/star-of-sun-519dddb6998545e2bf84225394dc71fe
title: Star Of Sun
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sun_LOD0__0: THREE.Mesh
    Sun_LOD1__0: THREE.Mesh
    Sun_LOD2__0: THREE.Mesh
    Sun_LOD3__0: THREE.Mesh
    Sun_LOD4__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export function Sun(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sun/star_of_sun-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[0, 0, -22.36]}>
            <mesh  geometry={nodes.Sun_LOD0__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[0, 0, -22.36]}>
            <mesh  geometry={nodes.Sun_LOD1__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[0, 0, -22.36]}>
            <mesh  geometry={nodes.Sun_LOD2__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[0, 0, -22.36]}>
            <mesh  geometry={nodes.Sun_LOD3__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[0, 0, -22.36]}>
            <mesh  geometry={nodes.Sun_LOD4__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sun/star_of_sun-transformed.glb')
