/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		Planet_13: THREE.Mesh
	}
	materials: {
		Material: THREE.MeshStandardMaterial
	}
}

export function Planet(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(
		'/models/planetAtom/PlanetAtom-transformed.glb'
	) as unknown as GLTFResult
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Planet_13.geometry}
				material={materials.Material}
			/>
		</group>
	)
}

useGLTF.preload('/models/planetAtom/PlanetAtom-transformed.glb')
